/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        bg:          'var(--color-bg)',
        surface:     'var(--color-surface)',
        card:        'var(--color-card)',
        ink:         'var(--color-ink)',
        foreground:  'var(--color-foreground)',
        muted:       'var(--color-muted)',
        primary:     'var(--color-primary)',
        secondary:   'var(--color-secondary)',
        accent:      'var(--color-accent)',
        border:      'var(--color-border)',
        destructive: 'var(--color-destructive)',
      },
      fontFamily: {
        mono:    ['var(--font-mono)', 'monospace'],
        sans:    ['var(--font-mono)', 'monospace'],
        serif:   ['var(--font-mono)', 'monospace'],
        display: ['var(--font-mono)', 'monospace'],
        body:    ['var(--font-mono)', 'monospace'],
      },
      borderRadius: {
        none: '0px',
        sm: '0px',
        DEFAULT: '0px',
        md: '0px',
        lg: '0px',
        xl: '0px',
        '2xl': '0px',
        '3xl': '0px',
        full: '0px',
      },
      maxWidth: {
        container: '1200px',
      },
      spacing: {
        '0.25': '1px',
        '1.75':  '7px',
        '2.25':  '9px',
        '2.75':  '11px',
        '3.5':   '14px',
        '4.5':   '18px',
        '5.5':   '22px',
        '5.25':  '21px',
        '6.5':   '26px',
        '7.5':   '30px',
        '8.25':  '33px',
        '8.5':   '34px',
        '13.5':  '54px',
        '18':    '72px',
        '22':    '88px',
        '30':    '120px',
      },
      lineHeight: {
        '4.5':  '18px',
        '5.5':  '22px',
        '5.25': '21px',
        '6':    '24px',
        '11':   '44px',
        '12':   '48px',
        '13.5': '54px',
        '18.5': '74px',
      },
      letterSpacing: {
        tightest: '-0.02em',
        tighter:  '-0.01em',
        normal: '0px',
      },
    },
  },
  plugins: [],
}
